### ISSUE TITLE
Create *Issue* template

### ISSUE THREAD

**Issue by tanyapowell** [tanyapowell/restaurant-reviews#4]
An **Issue** template helps us capture all the details the team will need to complete a task. 

The template can include (but is not limited to) a set of questions or headings that the person creating the new task needs to fill in.

- [Templates you could copy](https://github.com/stevemao/github-issue-templates)
- [Inspiration from other projects](https://github.com/devspace/awesome-github-templates)

**Comment by iesea** [comment]
Is there any further description to be added to this thread? I think this is expressing that something needs to be added to explain more about how to create an issue?

**Comment by tanyapowell** [comment]
Sure @iesea @hawa-bah I'll add a description of what needs to be done 😄
